### PR TITLE
UserPage - Search & Passward_Enhancement

### LINKED ISSUE #23: User Page - search book functionality

### LINKED ISSUE #30: Redundant point in adminPage.php
At the bottom of adminPage.php, there is a table that lists every book we have in the system, but there are lots of points before the table. This is because the echo contains a extra point in ' echo"</tr>."; '

### PR DESCRIPTION
**Pull request by TingYi88**
UserPage update

## Types of changes
- [x] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
I've update the user page, able to search with only one attribute, BUT required to absolute match all char ( if BookName == "10-Day Green Smoothie Cleanse", to search this book ,the only way is type "10-Day Green Smoothie Cleanse" in input )

By the way,I also fixed the bug 'come up with ...... while output', not only userPage, adminPage, db_search.php has this bug, I've fixed all of these bugs.
user page

the search outcome present like this.
user searched

## Related Issue
close #23 
close #30

### CODE REVIEW

**Review by Argentum11 — CHANGES_REQUESTED** [review]
Please keep the PR title simple and put the description under the title "Description"

**Comment by TingYi88** [comment]
OK, fixed. I just type everything on git commit. Don't Know what it actually worked like.

**Comment by Argentum11** [comment]
> OK, fixed. I just type everything on git commit. Don't Know what it actually worked like.

I'll teach you how to reset the commit and make a new commit with a simple title on Friday.

**Review by Argentum11 — APPROVED** [review]

**Review by Argentum11 — CHANGES_REQUESTED** [review]
1. You should click "New feature" better than "other" in Types of changes since you made the search and modify password functionality in this pull request
2. You didn't relate to the issue successfully, make sure the webpage pops up a list of PR and issue that you can choose from,  then click the one you want to relate to 
3. Please change the PR title again, there will be more updates for the userpage, you should use "UserPage - search and modify password" so that we could differentiate this PR from future userpage update by viewing the title instead of clicking inside this PR to look at details

**Review by TingYi88 — COMMENTED** [review]
now the user have to check the new passward one more time.
iff new passward and checked passward are the same can change the passward.

**Review by hong-511 — APPROVED** [review]

**Pull request merged**
